### ISSUE TITLE
Saved Recipes Not Appearing Until Refresh

### ISSUE THREAD

**Issue by cgouge93** [justinyates887/recipe-website#15]
Hey @selvivini. This looks wonderful! Thank you for your updates. Not sure if I just didn't pull updates correctly or what, but when testing I noticed that saved recipes don't appear in saved div until I refresh the page. Is this happening for you as well?

**Comment by selvivini** [comment]
yes this is happening to me as well..

**Comment by cgouge93** [comment]
Cool let's take a look at it together during class. I'm sure we can get it working no problem.

**Comment by selvivini** [comment]
thank you!

**Comment by cgouge93** [comment]
Created pull request with updated save button functionality.
